@TaskFlow.API_HostAddress = http://localhost:5181

POST {{TaskFlow.API_HostAddress}}/api/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Pedro",
  "email": "pedro@example.com",
  "password": "ChangeMe123"
}

###

POST {{TaskFlow.API_HostAddress}}/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "pedro@example.com",
  "password": "ChangeMe123"
}

###

@AccessToken = cole-o-token-aqui
@TaskId = cole-o-id-da-tarefa-aqui

PATCH {{TaskFlow.API_HostAddress}}/api/tasks/{{TaskId}}/status
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{AccessToken}}

{
  "status": 1
}

###

PATCH {{TaskFlow.API_HostAddress}}/api/tasks/{{TaskId}}/status
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{AccessToken}}

{
  "status": 2
}

###

PATCH {{TaskFlow.API_HostAddress}}/api/tasks/{{TaskId}}/status
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{AccessToken}}

{
  "status": 4
}

###
